#! /usr/bin/env bash

# status can be: Playing, Paused or Stopped
status=`dbus-send --print-reply \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.Get \
    string:'org.mpris.MediaPlayer2.Player' \
    string:'PlaybackStatus' \
    | egrep -A 1 "string" \
    | cut -b 26- \
    | cut -d '"' -f 1`

artist=`dbus-send --print-reply \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.Get \
    string:'org.mpris.MediaPlayer2.Player' \
    string:'Metadata' \
    | egrep -A 2 "artist" \
    | egrep -v "artist" \
    | egrep -v "array" \
    | cut -b 27- \
    | cut -d '"' -f 1`

album=`dbus-send --print-reply \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.Get \
    string:'org.mpris.MediaPlayer2.Player' \
    string:'Metadata' \
    | egrep -A 1 "album" \
    | egrep -v "album" \
    | cut -b 44- \
    | cut -d '"' -f 1`

title=`dbus-send --print-reply \
    --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.Get \
    string:'org.mpris.MediaPlayer2.Player' \
    string:'Metadata' \
    | egrep -A 1 "title" \
    | egrep -v "title" \
    | cut -b 44- \
    | cut -d '"' -f 1`

#    echo "Status : $status"
echo "Title  : $title"
echo "Artist : $artist"
echo "Album  : $album"

# vim: ft=sh
